language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - "5.0"

git:
  depth: 10

branches:
  only:
    - master

sudo: false

env:
  - CC=clang CXX=clang++ npm_config_clang=1
